title: Chandrasekaran aka CSKN
logo: /assets/img/logo2.png
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/cskn/">LinkedIn</a> |
  <a href="https://github.com/cskn1097">GitHub</a>
  <br>   
  Software Engineer currently pursuing MS in Machine Learning and Artificial Intelligence.
  Indusrry EXperience - 3.8 Years
  <br> 
  </p>
  
  
  



theme: jekyll-theme-minimal
