title: Chandrasekaran Baskaran
logo: /assets/img/logo4.png
description:
<p align="center">
<a href="pdf/resume.pdf">Resume</a> |
<a href="https://www.linkedin.com/in/cskn/">LinkedIn</a> |
<a href="https://github.com/cskn1097">GitHub</a>

Software Engineer currently pursuing MS in Machine Learning and Artificial Intelligence.
Industry Experience - 3.8 Years 
</p>
  
  
  



theme: jekyll-theme-minimal
